Adds checks for shebang and encoding correctness

diff --git a/tools/infrastructure/git-hooks/pre-commit b/tools/infrastructure/git-hooks/pre-commit
--- a/tools/infrastructure/git-hooks/pre-commit
+++ b/tools/infrastructure/git-hooks/pre-commit
@@ -1,5 +1,29 @@
 #!/bin/bash
 
+TEXT_DEFAULT="\\033[0;39m"
+TEXT_INFO="\\033[1;32m"
+TEXT_ERROR="\\033[1;31m"
+TEXT_UNDERLINE="\\0033[4m"
+TEXT_BOLD="\\0033[1m"
+
+PYTHON_FILES_NUMBER=$(git diff --name-only --cached | grep -e '\.py$' | wc -l)
+
+PYTHON_VERSION="python2$"
+PYTHON_VERSION_MATCHES=$(head -n1 $(git diff --name-only --cached | grep -e '\.py$') | grep -i $PYTHON_VERSION | wc -l)
+
+if [ "$PYTHON_VERSION_MATCHES" -ne "$PYTHON_FILES_NUMBER" ]; then
+    echo -e "${TEXT_ERROR}Some python file(s) have wrong shebang. Expected is:${TEXT_DEFAULT} ${TEXT_BOLD} $PYTHON_VERSION ${TEXT_DEFAULT}"
+    exit 2
+fi
+
+PYTHON_ENCODING="utf-8"
+PYTHON_CODE_PAGE_MATCHES=$(file --mime-encoding $(git diff --name-only --cached | grep -e '\.py$') | grep -i $PYTHON_ENCODING | wc -l)
+
+if [ "$PYTHON_CODE_PAGE_MATCHES" -ne "$PYTHON_FILES_NUMBER" ]; then
+    echo -e "${TEXT_ERROR}Some python file(s) have wrong encoding. Expected is:${TEXT_DEFAULT} ${TEXT_BOLD} $PYTHON_ENCODING ${TEXT_DEFAULT}"
+    exit 2
+fi
+
 # Hide all unstaged changes to prevent any influence of the further checks
 function POP_STASHED() {
     # pop stashed changes if working directory isn't clean
